### PR TITLE
docs: (IAC-837) Add clarification text for V4_CFG_MANAGE_STORAGE settings

### PR DESCRIPTION
**Pull request by dhoucgitter**
### Change
Create the draft of new doc to be added to the `Storage` and `PostgreSQL` sections of CONFIG-VARS.md to help explain viya4-deploy behavior and expectations when setting values for the `V4_CFG_MANAGE_STORAGE` variable.

### CODE REVIEW

**Comment by dhoucgitter** [comment]
Hi @supear, here's the doc PR that Thomas reached out to you for help with this afternoon. Would appreciate any suggestions that you have while it get reviewed.

**Comment by jkmin96** [comment]
Should we use "viya4-deployment" instead of "viya4-deploy"?

**Review by thpang — COMMENTED** [review]
I understand what you're trying to say it's a bit clunky. Setup a meeting with Susan. She stated she was free today so we can knock this out and get the wording in one pass. Thx.

**Comment by dhoucgitter** [comment]
> Should we use "viya4-deployment" instead of "viya4-deploy"? You also already used "viya4-deploy" in other places in https://github.com/sassoftware/viya4-deployment/blob/stagingplus/docs/CONFIG-VARS.md. However, if you see the main page (https://github.com/sassoftware/viya4-deployment/tree/stagingplus), it only uses "viya4-deployment".

@jkmin96 each of the viy4-deploy refs were updated to use viya4-deployment instead

**Comment by dhoucgitter** [comment]
Closing this as PR #373 supersedes it and targets the staging branch instead.

**Pull request closed without merging**
