### PR TITLE
(IAC-528) added git share directive for viya4-deployment

### PR DESCRIPTION
**Pull request by thpang**
Fixes this issue : https://github.blog/2022-04-12-git-security-vulnerability-announced/

### CODE REVIEW

**Comment by thpang** [comment]
This needs testing just added the code snippet needed to start moving forward on this one.

**Comment by thpang** [comment]
Best way to test. Create the new docker image. Run a container with that image using the entry point `bash` then
```bash
cat .gitconfig
```
You should see output showing a section with the label `[safe]` and the correct directory.

**Review by jarpat — APPROVED** [review]
Looks good, see internal ticket IAC-528 for testing.

**Review by sayeun — APPROVED** [review]
Based on the test results, I approved the change.

**Pull request merged**
