### PR TITLE
docs: (IAC-692) Multi-tenancy README updates from Pub

### PR DESCRIPTION
**Pull request by riragh**
# Changes:
No process change, just rewording and additional information updates to the existing README and CONFIG-VARS.md

### CODE REVIEW

**Comment by thpang** [comment]
Are these updates from Pubs? Someone from pubs usually forks the repo, makes the changes and then creates a pr. Wanting to make sure we're following process.

**Comment by sayeun** [comment]
A lot of changes are around the use of casing in multi-tenant and multi-tenancy.  Looks like it was decided Multi-tenancy is lower case t, and Multi-Tenant is an upper T.  I am seeing some inconsistency in the use of casing even in the Viya docs.  I would like to know what is the casing standard here.

**Review by thpang — APPROVED** [review]
LGTM

**Review by sayeun — APPROVED** [review]
👍

**Pull request merged**
