### PR TITLE
docs: (IAC-1462) remove references to multi-tenancy documentation

### PR DESCRIPTION
**Pull request by riragh**
## Changes:
SAS Viya currently has pause the support for Multi-tenancy, so all the references to Multi-tenancy documentation have been removed.

### CODE REVIEW

**Comment by jarpat** [comment]
@riragh should the example file be removed as well?

**Review by thpang — APPROVED** [review]

**Comment by dhoucgitter** [comment]
> @riragh should the example file be removed as well?

good point, not sure why we'd want to keep that if deleting the doc files.

**Comment by riragh** [comment]
So the idea is to keep the code in as is, just remove the doc references. So this would be like undocumented feature. I am not sure if example file would be considered as doc or code. If we you all think we should remove I am good to remove. Please let me know.

**Comment by dhoucgitter** [comment]
> @jarpat, @dhoucgitter So the idea is to keep the code in as is, just remove the doc references. So this would be like undocumented feature. I am not sure if example file would be considered as doc or code. If we you all think we should remove I am good to remove. Please let me know.

I suspect that if our intent is that the MT behavior/code should still be in place to support using Multi-Tenancy, just not document how to do that, then removing the example file is probably not a good idea.

**Review by dhoucgitter — APPROVED** [review]

**Review by jarpat — APPROVED** [review]

**Pull request merged**
