### PR TITLE
(IAC-333) Adding in hsts-max-age for security compliance.

### PR DESCRIPTION
**Pull request by thpang**

### CODE REVIEW

**Comment by thpang** [comment]
Not quite sure why `main` and `staging` are so off such that the merge has conflicts. Will work through these. Will be testing on Wed.

**Comment by sayeun** [comment]
The diff between main and staging is from https://github.com/sassoftware/viya4-deployment/pull/202/files

**Comment by thpang** [comment]
Validated that the config map of the ingress controller now sets the value to approximately 2 years.
```yaml
data:
  allow-snippet-annotations: 'true'
  hsts-max-age: '63072000'
  use-forwarded-headers: 'true'
```

**Comment by thpang** [comment]
Testing now shows with TLS active that the hsts-max-age is now part of the header response:

image

**Review by jarpat — APPROVED** [review]
Looks good just need to change the target to staging.

**Review by riragh — APPROVED** [review]
LGTM

**Comment by thpang** [comment]
Looking to have this one closed. Not sure what/how the merge branch was changed from staging to main. Guessing since the last release the staging branch was deleted. This might cause issues in the future for work that has been targeted for merge into staging but did not make the cut for that release.

**Pull request merged**
